version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: python code.py
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout  # Pull latest code from GitHub
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
