version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: python my_code.py
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout  # Pull latest code from GitHub
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest test.py
  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - run: echo "deploying on production"
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
             - test
          filters:
            branches:
              only:
               - main
               
